#!/usr/bin/env bash
# C-like script
i=0
while (( i < 10 )); do
  if (( i == 7 )); then
    echo "good luck"
  elif (( i == 3 )); then
    echo "bad luck"
  else
    echo "Best School"
  fi
  ((i++))
done

