#!/usr/bin/env bash
#Process and PID

echo $$ > /var/run/myscript.pid

term_handler() {
  echo "I hate the kill command"
  rm -f /var/run/myscript.pid
  exit
}

quit_handler() {
  rm -f /var/run/myscript.pid
  exit
}

trap 'echo "Y U no love me?!";' INT
trap term_handler TERM
trap quit_handler QUIT

while true
do
  echo "To infinity and beyond"
  sleep 2
done

